# Generated by Django 2.2.13 on 2021-01-31 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investor', '0001_initial'),
        ('borrower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='null', max_length=100)),
                ('Id_borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrower.Borrower')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_date', models.FloatField()),
                ('date1', models.DateField()),
                ('date2', models.DateField()),
                ('date3', models.DateField()),
                ('date4', models.DateField()),
                ('date5', models.DateField()),
                ('date6', models.DateField()),
                ('Id_borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='borrower.Borrower')),
                ('Id_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.Investor')),
                ('Id_loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanOperations.LoanRequest')),
            ],
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment1', models.BooleanField(default=False)),
                ('payment2', models.BooleanField(default=False)),
                ('payment3', models.BooleanField(default=False)),
                ('payment4', models.BooleanField(default=False)),
                ('payment5', models.BooleanField(default=False)),
                ('payment6', models.BooleanField(default=False)),
                ('Id_submit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanOperations.LoanSubmit')),
            ],
        ),
        migrations.CreateModel(
            name='LoanInvestorOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id_investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investor.Investor')),
                ('Id_loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loanOperations.LoanRequest')),
            ],
        ),
    ]
